# Default Configuration - Use profiles for environment-specific settings
spring:
  profiles:
    active: dev
  
  application:
    name: interview-api
  
  # Database Configuration (Common)
  datasource:
    driver-class-name: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  
  sql:
    init:
      mode: always
      data-locations: classpath:database/data.sql
  

# Application Information
info:
  app:
    name: interview-api
    version: 1.0-SNAPSHOT
    description: Customer Management API

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration (Common)
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{correlationId:-}] %-5level %logger{36} - %msg%n"
