# Test Configuration - Only test-specific overrides
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always

# Logging Configuration (Test-specific)
logging:
  level:
    com.interview: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

# Server Configuration (Test-specific)
server:
  port: 0

# OpenAPI Configuration (Disabled in Test)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Actuator Configuration (Test-specific)
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
