# Test Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: never

# Logging Configuration
logging:
  level:
    com.interview: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

# Server Configuration
server:
  port: 0

# Security Configuration
spring:
  security:
    user:
      name: test
      password: test
      roles: ADMIN

# OpenAPI Configuration
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
